apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: tenant-demo
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: hermes-real-estate
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: hermes
  ports:
    - name: http
      port: 8080
      targetPort: http
