"""SQLite / PostgreSQL 快取 store — erd.dbml 的落地實現（REQ:DEPLOY:STORE + CR-2026-008）。

雙後端：
- 開發/測試 → SQLite（`connect("path")` / `connect(":memory:")`）。
- GKE 部署 → Cloud SQL Postgres（`connect("postgresql://...")`，psycopg）。
- erd.dbml 本即 PostgreSQL；SQLite 為其子集。**函式簽名與行為不變**（dialect 差異封裝在內）。

設計：
- 連線 per-call（讀多寫少；FastMCP 多執行緒安全）。
- ingested_at/recorded_at 以 DI 注入（時間可測）。
- 去重：lvr (district,trade_date,total_price,area_ping)；crime (district,category,period)；
  traffic (lat,lng,severity,occurred_at)。SQLite=INSERT OR IGNORE；PG=ON CONFLICT DO NOTHING。
- DI-7 provenance；DI-5 crime 無座標欄；traffic 半徑 bbox+haversine（精篩於 store）。
追溯: erd.dbml、changes/CR-2026-005、CR-2026-006、CR-2026-007/CR-2026-008。
"""
import math
import sqlite3
from pathlib import Path

# ── DDL（兩 dialect；欄位語意一致）────────────────────────────────
_SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS lvr_trades (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  district       TEXT NOT NULL,
  deal_type      TEXT NOT NULL DEFAULT 'sale',
  building_type  TEXT NOT NULL DEFAULT '',
  trade_date     TEXT NOT NULL,
  total_price    INTEGER,
  unit_price_net REAL,
  area_ping      REAL,
  parking_price  INTEGER NOT NULL DEFAULT 0,
  project_name   TEXT,
  source         TEXT NOT NULL,
  data_as_of     TEXT NOT NULL,
  ingested_at    TEXT NOT NULL,
  UNIQUE (district, trade_date, total_price, area_ping)
);
CREATE INDEX IF NOT EXISTS ix_lvr_district_date ON lvr_trades (district, trade_date);

CREATE TABLE IF NOT EXISTS crime_area_stats (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  district    TEXT NOT NULL,
  category    TEXT NOT NULL,
  count       INTEGER NOT NULL,
  period      TEXT NOT NULL,
  source      TEXT NOT NULL,
  as_of       TEXT NOT NULL,
  ingested_at TEXT NOT NULL,
  UNIQUE (district, category, period)
);
CREATE INDEX IF NOT EXISTS ix_crime_district ON crime_area_stats (district, category);

CREATE TABLE IF NOT EXISTS traffic_accidents (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  lat         REAL NOT NULL,
  lng         REAL NOT NULL,
  severity    TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  source      TEXT NOT NULL,
  as_of       TEXT NOT NULL,
  ingested_at TEXT NOT NULL,
  UNIQUE (lat, lng, severity, occurred_at)
);
CREATE INDEX IF NOT EXISTS ix_acc_latlng ON traffic_accidents (lat, lng);

CREATE TABLE IF NOT EXISTS provenance (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_type TEXT NOT NULL,
  entity_ref  TEXT NOT NULL,
  source      TEXT NOT NULL,
  authority   TEXT NOT NULL,
  confidence  REAL NOT NULL,
  as_of       TEXT NOT NULL,
  recorded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_prov_entity ON provenance (entity_type, entity_ref);
"""

_PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS lvr_trades (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district       TEXT NOT NULL,
  deal_type      TEXT NOT NULL DEFAULT 'sale',
  building_type  TEXT NOT NULL DEFAULT '',
  trade_date     TEXT NOT NULL,
  total_price    BIGINT,
  unit_price_net DOUBLE PRECISION,
  area_ping      DOUBLE PRECISION,
  parking_price  BIGINT NOT NULL DEFAULT 0,
  project_name   TEXT,
  source         TEXT NOT NULL,
  data_as_of     TEXT NOT NULL,
  ingested_at    TEXT NOT NULL,
  UNIQUE (district, trade_date, total_price, area_ping)
);
CREATE INDEX IF NOT EXISTS ix_lvr_district_date ON lvr_trades (district, trade_date);

CREATE TABLE IF NOT EXISTS crime_area_stats (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district    TEXT NOT NULL,
  category    TEXT NOT NULL,
  count       INTEGER NOT NULL,
  period      TEXT NOT NULL,
  source      TEXT NOT NULL,
  as_of       TEXT NOT NULL,
  ingested_at TEXT NOT NULL,
  UNIQUE (district, category, period)
);
CREATE INDEX IF NOT EXISTS ix_crime_district ON crime_area_stats (district, category);

CREATE TABLE IF NOT EXISTS traffic_accidents (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat         DOUBLE PRECISION NOT NULL,
  lng         DOUBLE PRECISION NOT NULL,
  severity    TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  source      TEXT NOT NULL,
  as_of       TEXT NOT NULL,
  ingested_at TEXT NOT NULL,
  UNIQUE (lat, lng, severity, occurred_at)
);
CREATE INDEX IF NOT EXISTS ix_acc_latlng ON traffic_accidents (lat, lng);

CREATE TABLE IF NOT EXISTS provenance (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_ref  TEXT NOT NULL,
  source      TEXT NOT NULL,
  authority   TEXT NOT NULL,
  confidence  DOUBLE PRECISION NOT NULL,
  as_of       TEXT NOT NULL,
  recorded_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_prov_entity ON provenance (entity_type, entity_ref);
"""


# ── dialect 封裝 ───────────────────────────────────────────────
def _dialect(conn) -> str:
    return "postgres" if type(conn).__module__.split(".")[0] == "psycopg" else "sqlite"


def _pp(dialect: str) -> str:
    """positional placeholder。"""
    return "%s" if dialect == "postgres" else "?"


def _ph(dialect: str, name: str) -> str:
    """named placeholder。"""
    return f"%({name})s" if dialect == "postgres" else f":{name}"


def _build_insert(dialect: str, table: str, cols: list[str], conflict: list[str]) -> str:
    placeholders = ", ".join(_ph(dialect, c) for c in cols)
    collist = ", ".join(cols)
    if dialect == "sqlite":
        return f"INSERT OR IGNORE INTO {table} ({collist}) VALUES ({placeholders})"
    return (f"INSERT INTO {table} ({collist}) VALUES ({placeholders}) "
            f"ON CONFLICT ({', '.join(conflict)}) DO NOTHING")


def _exec_many(conn, dialect: str, sql: str, params: list[dict]) -> int:
    """executemany → 回實際新增筆數（去重後）。"""
    if dialect == "sqlite":
        before = conn.total_changes
        conn.executemany(sql, params)
        return conn.total_changes - before
    with conn.cursor() as cur:
        cur.executemany(sql, params)
        return cur.rowcount if (cur.rowcount or 0) >= 0 else len(params)


# ── 連線 / schema ──────────────────────────────────────────────
def connect(url: str):
    """SQLite 路徑/':memory:'（預設）或 'postgresql://...'（Cloud SQL）。"""
    if url.startswith(("postgres://", "postgresql://")):
        import psycopg
        from psycopg.rows import dict_row
        return psycopg.connect(url, row_factory=dict_row)
    if url != ":memory:":
        Path(url).expanduser().resolve().parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(url)
    conn.row_factory = sqlite3.Row
    return conn


def init_schema(conn) -> None:
    if _dialect(conn) == "sqlite":
        conn.executescript(_SQLITE_SCHEMA)
    else:
        for stmt in _PG_SCHEMA.split(";"):
            if stmt.strip():
                conn.execute(stmt)
    conn.commit()


# ── provenance（DI-7）─────────────────────────────────────────
def record_provenance(conn, entity_type: str, entity_ref: str, source: str,
                      authority: str, confidence: float, as_of: str, recorded_at: str) -> None:
    d = _dialect(conn)
    cols = ["entity_type", "entity_ref", "source", "authority", "confidence", "as_of", "recorded_at"]
    sql = (f"INSERT INTO provenance ({', '.join(cols)}) "
           f"VALUES ({', '.join(_ph(d, c) for c in cols)})")
    conn.execute(sql, {"entity_type": entity_type, "entity_ref": entity_ref, "source": source,
                       "authority": authority, "confidence": confidence, "as_of": as_of,
                       "recorded_at": recorded_at})


def query_provenance(conn, entity_type: str) -> list[dict]:
    pp = _pp(_dialect(conn))
    cur = conn.execute(f"SELECT * FROM provenance WHERE entity_type={pp} ORDER BY id", (entity_type,))
    return [dict(r) for r in cur.fetchall()]


# ── lvr_trades ────────────────────────────────────────────────
def upsert_lvr_trades(conn, rows: list[dict], source: str, data_as_of: str, ingested_at: str) -> int:
    d = _dialect(conn)
    cols = ["district", "deal_type", "building_type", "trade_date", "total_price",
            "unit_price_net", "area_ping", "parking_price", "project_name",
            "source", "data_as_of", "ingested_at"]
    sql = _build_insert(d, "lvr_trades", cols, ["district", "trade_date", "total_price", "area_ping"])
    params = [{
        "district": r["district"], "deal_type": r.get("deal_type", "sale"),
        "building_type": r.get("building_type", ""), "trade_date": r["trade_date"],
        "total_price": r.get("total_price"), "unit_price_net": r.get("unit_price_net"),
        "area_ping": r.get("area_ping"), "parking_price": r.get("parking_price", 0),
        "project_name": r.get("project_name"), "source": source,
        "data_as_of": data_as_of, "ingested_at": ingested_at,
    } for r in rows]
    added = _exec_many(conn, d, sql, params)
    record_provenance(conn, "lvr_trade", data_as_of, source, "gov", 1.0, data_as_of, ingested_at)
    conn.commit()
    return added


def query_lvr_comps(conn, district: str) -> list[dict]:
    pp = _pp(_dialect(conn))
    cur = conn.execute(f"SELECT * FROM lvr_trades WHERE district={pp} ORDER BY trade_date", (district,))
    return [dict(r) for r in cur.fetchall()]


# ── crime_area_stats（DI-5：無座標欄）──────────────────────────
def upsert_crime_area_stats(conn, district: str, stats: list[dict], source: str,
                            as_of: str, ingested_at: str) -> int:
    d = _dialect(conn)
    cols = ["district", "category", "count", "period", "source", "as_of", "ingested_at"]
    sql = _build_insert(d, "crime_area_stats", cols, ["district", "category", "period"])
    params = [{
        "district": district, "category": s["category"], "count": s["count"],
        "period": s.get("period", as_of), "source": source, "as_of": as_of, "ingested_at": ingested_at,
    } for s in stats]
    added = _exec_many(conn, d, sql, params)
    record_provenance(conn, "crime_area_stat", district, source, "gov", 1.0, as_of, ingested_at)
    conn.commit()
    return added


def query_crime_stats(conn, district: str) -> list[dict]:
    pp = _pp(_dialect(conn))
    cur = conn.execute(
        f"SELECT category, count, period FROM crime_area_stats WHERE district={pp} ORDER BY category",
        (district,),
    )
    return [dict(r) for r in cur.fetchall()]


# ── traffic_accidents（DI-5：點位入庫供聚合，tool 不回個別點）──────
def _haversine_m(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    r = 6_371_000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = math.radians(lat2 - lat1), math.radians(lng2 - lng1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def upsert_traffic_accidents(conn, rows: list[dict], source: str, as_of: str, ingested_at: str) -> int:
    d = _dialect(conn)
    cols = ["lat", "lng", "severity", "occurred_at", "source", "as_of", "ingested_at"]
    sql = _build_insert(d, "traffic_accidents", cols, ["lat", "lng", "severity", "occurred_at"])
    params = [{
        "lat": r["lat"], "lng": r["lng"], "severity": r["severity"],
        "occurred_at": r["occurred_at"], "source": source, "as_of": as_of, "ingested_at": ingested_at,
    } for r in rows]
    added = _exec_many(conn, d, sql, params)
    record_provenance(conn, "traffic_accident", as_of, source, "gov", 1.0, as_of, ingested_at)
    conn.commit()
    return added


def query_accident_points_near(conn, lat: float, lng: float, radius_m: float) -> list[dict]:
    """半徑內事故點（bbox 粗篩 + haversine 精篩）。**內部用**：呼叫端須聚合後輸出（DI-5）。"""
    pp = _pp(_dialect(conn))
    deg_lat = radius_m / 111_320.0
    deg_lng = radius_m / (111_320.0 * max(math.cos(math.radians(lat)), 1e-6))
    cur = conn.execute(
        f"SELECT lat, lng, severity, occurred_at FROM traffic_accidents "
        f"WHERE lat BETWEEN {pp} AND {pp} AND lng BETWEEN {pp} AND {pp}",
        (lat - deg_lat, lat + deg_lat, lng - deg_lng, lng + deg_lng),
    )
    out: list[dict] = []
    for r in cur.fetchall():
        if _haversine_m(lat, lng, r["lat"], r["lng"]) <= radius_m:
            out.append(dict(r))
    return out
