apiVersion: v1
kind: Service
metadata:
  name: envoy-egress
  namespace: gateway
  labels:
    app.kubernetes.io/name: envoy-egress
    app.kubernetes.io/part-of: hermes-real-estate
spec:
  selector:
    app.kubernetes.io/name: envoy-egress
  ports:
    - name: egress
      port: 10000
      targetPort: egress
